package com.aqupd.noteblockheads;

import net.minecraft.sound.SoundEvent;
import net.minecraft.sound.SoundEvents;

import java.util.HashMap;

public class Heads {
  public static HashMap<String, SoundEvent> HEADS = new HashMap<>() {{
    put("Allay", SoundEvents.ENTITY_ALLAY_AMBIENT_WITHOUT_ITEM);
    put("Bat", SoundEvents.ENTITY_BAT_AMBIENT);
    put("Bee", SoundEvents.ENTITY_BEE_LOOP);
    put("Blaze", SoundEvents.ENTITY_BLAZE_AMBIENT);
    put("Cat", SoundEvents.ENTITY_CAT_AMBIENT);
    put("Spider", SoundEvents.ENTITY_SPIDER_AMBIENT);
    put("Chicken", SoundEvents.ENTITY_CHICKEN_AMBIENT);
    put("Cod", SoundEvents.ENTITY_COD_FLOP);
    put("Cow", SoundEvents.ENTITY_COW_AMBIENT);
    put("Charged Creeper", SoundEvents.ENTITY_CREEPER_PRIMED);
    put("Dolphin", SoundEvents.ENTITY_DOLPHIN_AMBIENT);
    put("Donkey", SoundEvents.ENTITY_DONKEY_AMBIENT);
    put("Drowned", SoundEvents.ENTITY_DROWNED_AMBIENT);
    put("Elder Guardian", SoundEvents.ENTITY_ELDER_GUARDIAN_AMBIENT);
    put("Enderman", SoundEvents.ENTITY_ENDERMAN_AMBIENT);
    put("Endermite", SoundEvents.ENTITY_ENDERMITE_AMBIENT);
    put("Evoker", SoundEvents.ENTITY_EVOKER_AMBIENT);
    put("Fox", SoundEvents.ENTITY_FOX_AMBIENT);
    put("Frog", SoundEvents.ENTITY_FROG_AMBIENT);
    put("Ghast", SoundEvents.ENTITY_GHAST_AMBIENT);
    put("Glow Squid", SoundEvents.ENTITY_GLOW_SQUID_AMBIENT);
    put("Goat", SoundEvents.ENTITY_GOAT_AMBIENT);
    put("Screaming Goat", SoundEvents.ENTITY_GOAT_SCREAMING_AMBIENT);
    put("Guardian", SoundEvents.ENTITY_GUARDIAN_AMBIENT);
    put("Hoglin", SoundEvents.ENTITY_HOGLIN_AMBIENT);
    put("Horse", SoundEvents.ENTITY_HORSE_AMBIENT);
    put("Husk", SoundEvents.ENTITY_HUSK_AMBIENT);
    put("Illusioner", SoundEvents.ENTITY_ILLUSIONER_AMBIENT);
    put("Iron Golem", SoundEvents.ENTITY_IRON_GOLEM_DAMAGE);
    put("Llama", SoundEvents.ENTITY_LLAMA_AMBIENT);
    put("Magma Cube", SoundEvents.ENTITY_MAGMA_CUBE_SQUISH);
    put("Mooshroom", SoundEvents.ENTITY_MOOSHROOM_SUSPICIOUS_MILK);
    put("Mule", SoundEvents.ENTITY_MULE_AMBIENT);
    put("Ocelot", SoundEvents.ENTITY_OCELOT_AMBIENT);
    put("Panda", SoundEvents.ENTITY_PANDA_AMBIENT);
    put("Weak Panda", SoundEvents.ENTITY_PANDA_SNEEZE);
    put("Parrot", SoundEvents.ENTITY_PARROT_AMBIENT);
    put("Phantom", SoundEvents.ENTITY_PHANTOM_AMBIENT);
    put("Pig", SoundEvents.ENTITY_PIG_AMBIENT);
    put("Piglin", SoundEvents.ENTITY_PIGLIN_AMBIENT);
    put("Piglin Brute", SoundEvents.ENTITY_PIGLIN_BRUTE_AMBIENT);
    put("Pillager", SoundEvents.ENTITY_PILLAGER_AMBIENT);
    put("Polar Bear", SoundEvents.ENTITY_POLAR_BEAR_AMBIENT);
    put("Pufferfish", SoundEvents.ENTITY_PUFFER_FISH_FLOP);
    put("Rabbit", SoundEvents.ENTITY_RABBIT_AMBIENT);
    put("Ravager", SoundEvents.ENTITY_RAVAGER_AMBIENT);
    put("Salmon", SoundEvents.ENTITY_SALMON_FLOP);
    put("Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT);
    put("Shulker", SoundEvents.ENTITY_SHULKER_AMBIENT);
    put("Silverfish", SoundEvents.ENTITY_SILVERFISH_AMBIENT);
    put("Skeleton Horse", SoundEvents.ENTITY_SKELETON_HORSE_AMBIENT);
    put("Slime", SoundEvents.ENTITY_SLIME_SQUISH);
    put("Snow Golem", SoundEvents.ENTITY_SNOW_GOLEM_AMBIENT);
    put("Squid", SoundEvents.ENTITY_SQUID_AMBIENT);
    put("Stray", SoundEvents.ENTITY_STRAY_AMBIENT);
    put("Strider", SoundEvents.ENTITY_STRIDER_AMBIENT);
    put("Tadpole", SoundEvents.ENTITY_TADPOLE_FLOP);
    put("Tropical Fish", SoundEvents.ENTITY_TROPICAL_FISH_FLOP);
    put("Turtle", SoundEvents.ENTITY_TURTLE_AMBIENT_LAND);
    put("Vex", SoundEvents.ENTITY_VEX_AMBIENT);
    put("Villager", SoundEvents.ENTITY_VILLAGER_AMBIENT);
    put("Vindicator", SoundEvents.ENTITY_VINDICATOR_AMBIENT);
    put("Wandering Trader", SoundEvents.ENTITY_WANDERING_TRADER_AMBIENT);
    put("Warden", SoundEvents.ENTITY_WARDEN_AMBIENT);
    put("Witch", SoundEvents.ENTITY_WITCH_AMBIENT);
    put("Wither", SoundEvents.ENTITY_WITHER_AMBIENT);
    put("Wolf", SoundEvents.ENTITY_WOLF_AMBIENT);
    put("Zoglin", SoundEvents.ENTITY_ZOGLIN_AMBIENT);
    put("Zombie Horse", SoundEvents.ENTITY_ZOMBIE_HORSE_AMBIENT);
    put("Zombified Piglin", SoundEvents.ENTITY_ZOMBIFIED_PIGLIN_AMBIENT);

    //Zombie Villagers
    put("Zombie Armorer", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT);
    put("Zombie Butcher", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT);
    put("Zombie Cartographer", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT);
    put("Zombie Cleric", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT);
    put("Zombie Farmer", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT);
    put("Zombie Fisherman", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT);
    put("Zombie Fletcher", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT);
    put("Zombie Leatherworker", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT);
    put("Zombie Librarian", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT);
    put("Zombie Mason", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT);
    put("Zombie Nitwit", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT);
    put("Zombie Villager", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT);
    put("Zombie Shepherd", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT);
    put("Zombie Toolsmith", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT);
    put("Zombie Weaponsmith", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT);
  }};
}
